export const endpointPaths = {
  health: '/api/health',
  metrics: '/api/metrics',
  localBootstrap: '/api/local/bootstrap',
  localDoctor: '/api/local/doctor',
  localReadiness: '/api/local/readiness',
  localAcceptanceStatus: '/api/local/acceptance-status',
  localSetupBundle: '/api/local/setup-bundle',
  configModels: '/api/config/models',
  providerCatalog: '/api/config/provider-catalog',
  configValidate: '/api/config/validate',
  modelCheck: '/api/config/model-check',
  comfyuiConnect: '/api/comfyui/connect',
  comfyuiDiscoverWorkflows: '/api/comfyui/discover-workflows',
  comfyuiOutputs: '/api/comfyui/outputs',
  runninghubCheck: '/api/runninghub/check',
  runs: '/api/runs',
  promptProfiles: '/api/prompt-profiles',
  promptProfile: (profileId: string) => `/api/prompt-profiles/${profileId}`,
  promptProfileClone: (profileId: string) =>
    `/api/prompt-profiles/${profileId}/clone`,
  promptProfileReset: (profileId: string) =>
    `/api/prompt-profiles/${profileId}/reset`,
  runDetail: (runId: string) => `/api/runs/${runId}`,
  runEvents: (runId: string) => `/api/runs/${runId}/events`,
  runTimeline: (runId: string) => `/api/runs/${runId}/timeline`,
  runArtifacts: (runId: string) => `/api/runs/${runId}/artifacts`,
  runRefreshComfyUI: (runId: string) => `/api/runs/${runId}/refresh-comfyui`,
  runApprove: (runId: string) => `/api/runs/${runId}/approve`,
  runRetry: (runId: string) => `/api/runs/${runId}/retry`,
  runCancel: (runId: string) => `/api/runs/${runId}/cancel`,
  batchPlan: '/api/batches/plan',
  batches: '/api/batches',
  batchDetail: (batchId: string) => `/api/batches/${batchId}`,
  batchTimeline: (batchId: string) => `/api/batches/${batchId}/timeline`,
  batchArtifacts: (batchId: string) => `/api/batches/${batchId}/artifacts`,
  batchRecoveryPlan: (batchId: string) =>
    `/api/batches/${batchId}/recovery-plan`,
  batchRecover: (batchId: string) => `/api/batches/${batchId}/recover`,
  batchExport: (batchId: string) => `/api/batches/${batchId}/export`,
  batchExportValidate: (batchId: string) =>
    `/api/batches/${batchId}/export/validate`,
  batchExportValidateZip: (batchId: string) =>
    `/api/batches/${batchId}/export/validate-zip`,
  batchRetry: (batchId: string) => `/api/batches/${batchId}/retry`,
  batchCancel: (batchId: string) => `/api/batches/${batchId}/cancel`,
  batchPause: (batchId: string) => `/api/batches/${batchId}/pause`,
  batchResume: (batchId: string) => `/api/batches/${batchId}/resume`,
  comfyuiAnalyzeWorkflow: '/api/comfyui/analyze-workflow',
} as const
